kind: Deployment
apiVersion: apps/v1
metadata:
  name: certs-expiration-check
  namespace: cert-check
  labels:
    app: certs-expiration-check
spec:
  replicas: 1
  selector:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: certs-expiration-check
    spec:
      restartPolicy: Always
      serviceAccountName: cert-check
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: certs-expiration-check
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/cert-check/certs-expiration-check:latest
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600