kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: certs-expiration-check
  namespace: cert-check
  labels:
    app: certs-expiration-check
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 12-ubi8
spec:
  lookupPolicy:
    local: false