apiVersion: v1
kind: Service
metadata:
  name: cert-check
  namespace: cert-check
spec:
  selector:
    app: certs-expiration-check
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080